### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by xzfc** [cachix/cachix-action#23]
I am getting the following error while using `cachix/cachix-action@v3`:

```
Run cachix/cachix-action@v3
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/cachix/cachix-action/v3/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v3/lib/main.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/cachix/cachix-action/v3/lib/main.js' ]
}
##[error]Node run failed with exit code 1
```

Test repo: https://github.com/xzfc/cachix-test/blob/12f9fa068234aed52f5888b77aafc6053d3979b6/.github/workflows/test.yml
https://github.com/xzfc/cachix-test/runs/358848998

Whereas `cachix/cachix-action@v2` works fine: https://github.com/xzfc/cachix-test/runs/358869757

**Comment by kutyel** [comment]
For now and until this is fixed, `cachix/cachix-action@releases/v3` works correctly 🆗

**Comment by domenkozar** [comment]
Should be fixed now, can you confirm?

**Comment by kutyel** [comment]
I can confirm it works, thanks! 🙌
