### ISSUE TITLE
experimental Nix feature 'nix-command' is disabled

### ISSUE THREAD

**Issue by zimbatm** [cachix/cachix-action#48]
Because the action is calling `nix path-info`, it might fail in some Nix installations.

```
/bin/sh -c nix path-info --all | grep -v '.drv$' > /tmp/store-path-pre-build
error: --- Error --- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
##[error]Action failed with error: Error: The process '/bin/sh' failed with exit code 1
(node:3014) UnhandledPromiseRejectionWarning: Error: The process '/bin/sh' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:907:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:890:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v6/dist/main/index.js:790:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:3014) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is only an issue when using https://github.com/numtide/nix-flakes-installer

**Comment by zimbatm** [comment]
If that happens, the workaround is to add this step before the cachix action:
```yaml
- run: echo "experimental-features = nix-command" | sudo tee -a /etc/nix/nix.conf
```

**Comment by domenkozar** [comment]
Sigh :) Will need to fix this before Nix 2.4 is released.

I think it's best to just enable nix-command, although we have to expose list of experimental  features to be appended.

**Comment by domenkozar** [comment]
Hope that https://github.com/NixOS/nix/pull/3744/files lands

**Comment by domenkozar** [comment]
Needs to pass `--experimental-features nix-command` but only when Nix version is greater than 2.4

**Comment by zimbatm** [comment]
I would do two things:

* add `extra_nix_config` flag to the install-nix-action. That's for users who want to enable other sorts of experimental options
* add feature detection in the cachix CLI itself. There is probably some logic in there already to detect single-user vs multi-user installations.

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nix/issues/4044
